#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Apache SystemML<sup id="trademark">&trade;</sup>
short_name: SystemML<sup id="trademark">&trade;</sup>
description: Apache SystemML<sup id="trademark">&trade;</sup> is a distributed and declarative machine learning platform.

dev_list: dev@systemml.apache.org
dev_list_subscribe: dev-subscribe@systemml.apache.org
dev_list_unsubscribe: dev-unsubscribe@systemml.apache.org
dev_list_archive: http://mail-archives.apache.org/mod_mbox/systemml-dev/
dev_list_archive_mailarchive: https://www.mail-archive.com/dev@systemml.apache.org/
dev_list_archive_markmail:

user_list:
user_list_subscribe:
user_list_unsubscribe:
user_list_archive:
user_list_archive_mailarchive:
user_list_archive_markmail:

commits_list: commits@systemml.apache.org
commits_list_subscribe: commits-subscribe@systemml.apache.org
commits_list_unsubscribe: commits-unsubscribe@systemml.apache.org
commits_list_archive: http://mail-archives.apache.org/mod_mbox/systemml-commits/
commits_list_archive_mailarchive: https://www.mail-archive.com/commits@systemml.apache.org/
commits_list_archive_markmail:

issues_list: issues@systemml.apache.org
issues_list_subscribe: issues-subscribe@systemml.apache.org
issues_list_unsubscribe: issues-unsubscribe@systemml.apache.org
issues_list_archive: http://mail-archives.apache.org/mod_mbox/systemml-issues/
issues_list_archive_mailarchive: https://www.mail-archive.com/issues@systemml.apache.org/
issues_list_archive_markmail:

jira: SYSTEMML

release_name: systemml
release_version: 0.15.0

source_repository: https://git-wip-us.apache.org/repos/asf/systemml.git
source_repository_mirror: https://github.com/apache/systemml

website_repository: https://git-wip-us.apache.org/repos/asf/systemml-website.git
website_repository_mirror: https://github.com/apache/systemml-website

download: /download.html

documentation: /documentation.html

podling: false
